---
# tasks file for grav-core
- name: Install Grav dependencies
  apt:
   name: "{{ item }}"
  with_items: 
    - "{{ grav_dependencies }}"
  tags:
    - install_dependencies

- name: Enable apache modules
  shell: a2enmod "{{ item }}"
  with_items: 
    - "{{ http_modules }}"
  notify: restart apache

- name: Template virtual host file to grav to proxy and redirects
  template:
    src: virtualhost.conf
    dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
  notify:
    - restart apache
  tags:
    - install_conf_file

- name: Download Grav skeleton {{ skeleton_name }} core
  get_url:
    url: "{{ grav_skeleton_site }}/{{ skeleton_name }}"
    dest: "{{ apache_web_path }}/{{ domain_name }}/"
  register: grav_download_filename
  tags: 
    - download_grav
  
- name: Install Grav core skeleton {{ skeleton_name }}
  unarchive:
    src: "{{ grav_download_filename.dest }}"
    dest: "{{ apache_web_path }}/{{ domain_name }}"
    remote_src: "yes"
    owner: www-data
    group: www-data
    mode: 0755
    list_files: "True"
  tags: 
    - install_grav
  register: archive_list

- set_fact:
    dir_name: "{{ archive_list.files[0] }}"
  tags:
    - get_file_name

- debug:
    var: archive_list.files[0]
  tags:
    - install_grav

- name: test move 
  shell: mv "{{ apache_web_path }}/{{ domain_name }}/{{ dir_name }}/\*.\*" "{{ apache_web_path }}/{{ domain_name }}/"
  tags:
   - move

