---
# tasks file for grav-core
- name: Download Grav skeleton {{ skeleton_name }} core
  get_url:
    url: "{{ grav_skeleton_site }}/{{ skeleton_name }}"
    dest: "{{ apache_web_path }}/{{ domain_name }}/"
  tags: download_grav
  register: grav_download_filename

- name: Obtain download filename
  debug:
    msg: "{{ grav_download_filename.dest }}"

- name: Install Grav core skeleton {{ skeleton_name }}
  unarchive:
    src: "{{ grav_download_filename.dest }}"
    dest: "{{ apache_web_path }}/{{ domain_name }}"
    remote_src: "yes"
    owner: www-data
    group: www-data
    mode: 0755
  tags: install_grav