---
# tasks file for grav-core
- name: Download Grav skeleton {{ skeleton_name }} core 
  get_url:
    url: "{{ grav_skeleton_site }}/{{ skeleton_name }}"
    dest: "/var/www/{{ domain_name }}/tmp"

- name: Install Grav core skeleton {{ skeleton_name }}
  unarchive:
    src: "/var/www/{{ domain_name }}/tmp/{{ skeleton_name }}"
    dest: "/var/www/{{ domain_name }}"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0755