---
# tasks file for logstash
- name: Install Elasticsearch public key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Update system 
  apt:
    update_cache: yes

# Required to install all elasticsearch products
- name: Install apt-transport-https
  package:
    name: apt-transport-https
    state: present

- name: Install logstash apt repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present
 
# Order of application installation is important
- name: Install Java aplications default-jre, default-jre-headless and logstash
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - default-jre-headless
    - default-jre
    - logstash