---
# tasks file for logstash
- name: Install Elasticsearch application key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Update system
  package:
    upgrade: yes
    update_cache: yes

- name: Install apt-repository
  package:
    name: apt-transport-https
    state: present

- name: Install logstash apt repository to systems source list
  template:
    src: logstash5-x.j2
    dest: /etc/apt/sources.list.d/logstash5.x.list
    mode: 0600
    owner: root
    group: root

- name: Update system
  package:
    upgrade: yes
    update_cache: yes

- name: Install Java aplications default-jre, default-jre-headless
  package:
    name: "{{item}}"
    state: present
  with_items:
    - default-jre
    - default-jre-headless

- name: Install logstash
  package:
    name: logstash
    state: present
