---
# tasks file for logstash
- name: Install Elasticsearch application key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Update system
  package:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install apt-repository
  package:
    name: apt-transport-https
    state: present

- name: Install Java aplications default-jre, default-jre-headless
  package:
    name: "{{item}}"
    state: present
  with_items:
    - default-jre
    - default-jre-headless

- name: Install logstash
  package:
    name: logstash
    state: present
