---
# tasks file for nginx
 - name: Add Nginx Repository
   apt_repository: repo='ppa:nginx/stable' state=present

 - name: Install Nginx
   apt: pkg=nginx state=installed update_cache=true
   notify:
    - Start Nginx

 - name: Add H5Bp config
   copy: src=h5bp dest=/etc/nginx owner=root group=root

 - name: Dsable Default config
   file: dest=/etc/nginx/sites-enabled/default state=absent
   notify:
    - Reload Nginx