---
# tasks file for nginx
 - name: Update system
   apt:
     update_cache: true

 - name: Install Nginx
   apt: 
     pkg: nginx 
     state: present
     update_cache: true
   notify:
    - Start Nginx

 - name: Add H5Bp config
   copy: 
     src: h5bp 
     dest: /etc/nginx 
     owner: root 
     group: root

 - name: Disable Default config
   file: 
     dest: /etc/nginx/sites-enabled/default 
     state: absent
   notify:
    - Reload Nginx