---
# tasks file for grav
- name: Update packages
  apt:
    update_cache: yes

- name: Install Grav dependencies
  apt:
   name: "{{ item }}"
  with_items: 
    - "{{ grav_dependencies }}"
  tags:
    - install_dependencies

- name: Instal Utility applications
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ utilities }}"
  tags:
    - install_utilities

- name: Download Grav core admin
  get_url:
    url: "{{ grav_package }}"
    dest: /tmp/grav-admin.zip
  tags:
    - download_grav

- name: Install Grav to {{ domain_name }}
  unarchive:
    src: /tmp/grav-admin.zip
    dest: "/var/www/{{ domain_name }}"
    remote_src: yes
  tags:
    - install_grav

- name: Enable apache modules
  shell: a2enmod "{{ item }}"
  with_items: 
    - "{{ http_modules }}"
  notify: restart apache

- name: Change domain {{ domain_name }} ownership to www-data
  file:
    path: "/var/www/{{ domain_name }}"
    owner: www-data
    group: www-data

- name: Change file permissions to 664
  shell: find "/var/www/{{ domain_name }}" -type f | xargs chmod 664
  tags:
    - grav_permissions

- name: Change directory permission to 0755
  shell: find "/var/www/{{ domain_name }}" -type d | xargs chmod 775
  tags:
    - grav_permissions

- name: Ensure secure file permission.
  shell: find "/var/www/{{ domain_name }}" -type d | xargs chmod +s
  tags:
    - grav_permissions

- name: Grant access to web server
  shell: cd "/var/www/{{ domain_name }}" && umask 0002
  tags:
    - grav_permissions

- name: Template out virtualhost file
  template:
    src: virtualhost.conf
    dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
  notify:
    - restart apache
  tags:
    - install_conf_file
