---
# tasks file for grav
- name: Update packages
  apt:
    update_cache: yes

- name: Install Grav dependencies
  apt:
   name: "{{ item }}"
  with_items: 
    - "{{ grav_dependencies }}"
  tags:
    - install_dependencies

- name: Instal Utility applications
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ utilities }}"
  tags:
    - install_utilities

- name: Download Grav core admin
  get_url:
    url: "{{ grav_package }}"
    dest: /tmp/grav-admin.zip
  tags:
    - download_grav

- name: Install Grav to {{ domain_name }}
  unarchive:
    src: /tmp/grav-admin.zip
    dest: "/var/www/{{ domain_name }}"
    remote_src: yes
  tags:
    - install_grav

- name: Grant access to web server user
  command: find "/var/www/{{ domain_name }}/" -type f | xargs chmod 664
  tags:
    - grav_permissions

- name: Grant access to web server user
  command: find "/var/www/{{ domain_name }}/" -type d | xargs chmod 775
  tags:
    - grav_permissions

- name: Grant access to web server user
  command: find "/var/www/{{ domain_name }}/" -type d | xargs chmod +s
  tags:
    - grav_permissions

- name: Grant access to web server
  command: cd "/var/www/{{ domain_name }}/" && umask 0002
  tags:
    - grav_permissions

- name: Enable apache modules
  apache2_module:
    name: "{{ http_modules }}"
    state: present
  notify: restart apache


  
