---
# tasks file for grav
- name: Update packages
  apt:
    update_cache: yes

- name: Install Grav dependencies
  apt:
   name: "{{ item }}"
  with_items: 
    - "{{ grav_dependencies }}"
  tags:
    - install_dependencies

- name: Instal Utility applications
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ utilities }}"
  tags:
    - install_utilities

- name: Download Grav core admin
  get_url:
    url: "{{ grav_package }}"
    dest: /tmp/grav-admin.zip
  tags:
    - download_grav

- name: Install Grav to /var/www/{{ domain_name }} directory
  unarchive:
    src: /tmp/grav-admin.zip
    dest: "/var/www/{{ domain_name }}"
    remote_src: yes
  tags:
    - install_grav

- name: Template virtual host file to grav to proxy and redirects
  template:
    src: virtualhost.conf
    dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
  notify:
    - restart apache
  tags:
    - install_conf_file

- name: Enable apache modules
  shell: a2enmod "{{ item }}"
  with_items: 
    - "{{ http_modules }}"
  notify: restart apache

- name: Enable Letsencrypt SSL certification for {{ domain_name }}
  shell: "certbot --{{ certbot_httpd }} -m cmills@opensitesolutions.com -d www.{{ domain_name }} -n --agree-tos"
  tags:
    - enable_cert
  notify:
    - restart apache
  when: skip is defined and skip == 'yes'

- name: Create Grav default user
  shell: "cd /var/www/{{ domain_name }}/grav-admin && bin/plugin login new-user -u {{ grav_user }} -p {{ grav_user_password }} -e {{ grav_user_email }} -P b -N {{ grav_user_fullname }} -t {{ grav_title }}"
  tags:
    - create_grav_user

- name: Update all plugins automatically 
  shell: "cd /var/www/{{ domain_name }}/grav-admin && bin/gpm update -f -y"
  tags:
    - update_grav

- name: Install themes
  shell: "cd /var/www/{{ domain_name }}/grav-admin && bin/gpm -y install {{ item }}"
  with_items:
    - "{{ theme_list }}"

- name: Change {{ domain_name }} ownership to www-data
  shell: cd "/var/www/{{ domain_name }}" && chown -R www-data:www-data *
  tags:
    - grav_permissions
    - update_grav

- name: Change file permissions on {{ domain_name }} to 0755
  file: 
    path: "/var/www/{{ domain_name }}/grav-admin"
    mode: 0755
    recurse: yes
  tags:
    - grav_permissions
    - update_grav
  
- name: Set umask to 0002
  shell: cd "/var/www/{{ domain_name }}" && umask 0002
  tags:
    - grav_permissions
    - update_grav