# Manage Packet servers and ssh keys
---
- name: create 1 device
  hosts: localhost
  connection: local
  vars:
    prescence: absent
  tasks:

  - name: Upload ssh key to packet host
    packet_sshkey:
      label: key from file
      key_file: ~/.ssh/id_rsa.pub
      state: "{{prescence}}"

  - name: Create a single packer instance
    packet_device:
      project_id: "{{proj_id}}"
      hostnames: myserver
      operating_system: ubuntu_14_04
      plan: baremetal_1
      facility: sjc1
      state: "{{prescence}}"
      wait_for_public_IPv: 4
    register: newhosts

  - name: wait for ssh port
    wait_for:
      delay: 1
      host: "{{ item.public_ipv4 }}"
      port: 22
      state: started
      timeout: 500
    with_items: "{{ newhosts.devices }}"
