---
# tasks file for mysql
- name: Install Mysql
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  tags:
    - install_mysql
  
- name: Remove mysql
  apt:
    name: mysql-server
    state: absent
    purge: yes
    autoremove: yes
  tags:
    - remove_mysql


