---
# tasks file for users

- name: Add users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.full_name }}"
    shell: "{{ default_shell }}"
    groups: sudo
    state: present
  with_items:
    - "{{ users }}"

- name: Set authorized keys for users
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  with_items:
    - "{{ users }}"

- name: Enable deployuser to use sudo without passwords
  template:
    src: sudo.j2
    dest: "/etc/sudoers.d/{{ item.username }}"
    owner: root
    group: root
    mode: 0600
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
     - "{{ users }}"
