---
# tasks file for users

- name: Create deployuser
  user:
    name: deployuser
    comment: "deployment user"
    shell: /bin/bash
    groups: sudo
    state: present

- name: Create cmills
  user:
    name: cmills
    comment: "Clarence Mills"
    shell: /bin/bash
    groups: sudo
    state: present

- name: Set authorized key for deployuser
  authorized_key:
    user: deployuser
    key: "{{ lookup('file', '/home/cmills/.ssh/id_rsa.pub') }}"

- name: Set authorized key for cmills
  authorized_key:
    user: cmills
    key: "{{ lookup('file', '/home/cmills/.ssh/id_rsa.pub') }}"

- name: Enable deployuser to use sudo without passwords
  template:
    src: sudo.j2
    dest: /etc/sudoers.d/deployuser
    owner: root
    group: root
    mode: 0600

- name: Enable cmills to use sudo without passwords
  template:
    src: sudo.j2
    dest: /etc/sudoers.d/cmills
    owner: root
    group: root
    mode: 0600
    validate: '/usr/sbin/visudo -cf %s'
