---
# vars file for elasticsearch
esearch: elasticsearch-2.4.5.deb
esearchlink: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.5/

apt_repo_url: 'deb https://packages.elastic.co/elasticsearch/2.x/debian stable main'
apt_key_url: https://packages.elastic.co/GPG-KEY-elasticsearch
