---
# vars file for elasticsearch
esearch: elasticsearch-2.4.5.deb
esearchlink: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.5/

kibana: kibana-6.1.1-linux-x86_64.tar.gz
kibanalink: https://artifacts.elastic.co/downloads/kibana/
