---
# defaults file for grav
grav_dependencies:
 - php-fpm
 - php-gd
 - php-curl
 - php-zip
 - php-xml
 - php-zip
 - php-mbstring
 - php7.2-mbstring

grav_package: https://getgrav.org/download/core/grav-admin/1.4.2

utilities:
 - unzip

http_modules:
 - rewrite
 - ssl