---
# tasks file for roles/httpd
- name: Install Httpd on debian based system
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Install Httpd on Redhat` based system
  include_tasks: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "CentOS"