---
# tasks file for httpd-domain-setup
- name: Create domain root directory
  file:
    src: "{{ web_dir }}"
    path: "{{ web_dir }}/{{ domain_name }}"
    state: directory
  tags:
    - virt_setup

- name: Create virtualhost file
  template:
    src: domain.j2
    dest: "{{ virt_dir }}/{{ domain_name }}.conf"
  tags:
    - virt_setup

- name: Enable {{ domain_name }}
  shell: a2ensite "{{ domain_name }}.conf"
  notify:
    - restart apache2
  tags:
    - virt_setup

- name: Install web utilities
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ web_utilities }}"
  tags:
    - install_web_utils