---
# Inatall elasticsearch
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install Elasticsearch apt apt_repository
  apt_repository:
    repo: 'deb https://packages.elastic.co/elasticsearch/2.x/debian stable main'
    state: present

- name: Install Elasticsearch application key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Update system
  apt:
    update_cache: yes

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present