---
# Inatall elasticsearch
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install Elasticsearch application key
  apt_key:
    url: "{{ apt_key_url }}"
    state: present

- name: Install Elasticsearch apt apt_repository
  apt_repository:
    repo: "{{ apt_repo_url }}"
    state: present

- name: Update system
  apt:
    update_cache: yes

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present