# The variable name is passed into this playbook using -e "name=choose a name"

---
 - hosts: '{{ servername }}'
   tasks:
   - name: Add user 1
     user:
       name: deployuser
       comment: "deployment user"
       hell: /bin/bash
       state: present

   - name: Set authorized key
     authorized_key:
       user: deployuser
       key: "{{ lookup('file', '/home/cmills/.ssh/id_rsa.pub') }}"
