# pass in variables for server_name and domain_name and repo_name
---
- hosts: "{{ server_name }}"  # Change this to the destination server name
  become: "true"
  remote_user: deployuser
  gather_facts: False
  vars:
    - web_dir: /var/www/
    - web_user: www-data
    - web_group: www-data
  tasks:

  - name: Delete remote {{ domain_name}} directory
    file:
      path: "{{ web_dir }}{{ domain_name }}"
      state: absent
    tags: 
      - publish

  - name: Download git repository from "(( repo_name }}"
    git:
      clone: "yes"
      depth: 1
      repo: "{{ repo_name }}"
      dest: "{{ web_dir }}{{ domain_name }}"
      force: "yes"
    tags:
      - publish
      
  - name: Assign permissions for www-data user
    file:
      path: "{{ web_dir }}{{ domain_name }}"
      recurse: "yes"
      owner: "{{ web_user }}"
      group: "{{ web_group }}"
      mode: 0775
    tags:
      - publish
